#!/bin/bash

apply_default_config() {
  dokuwiki_original_conf=$ISOWIKI_ROOT_DIR/conf/dokuwiki.php
  dokuwiki_local_conf=$APACHE_SERVER_ROOT/conf/dokuwiki.php

  echo cp "$dokuwiki_original_conf" "$dokuwiki_local_conf"
  cp "$dokuwiki_original_conf" "$dokuwiki_local_conf"

  # https://stackoverflow.com/questions/1527049/how-can-i-join-elements-of-an-array-in-bash
  function join_by { local IFS="$1"; shift; echo "$*"; }

  IFS=$'\n'
  for var in $(printenv|grep '^DOKUWIKI_'); do
    var_name="${var%%=*}"
    IFS="_" read -a parts <<< $var_name
    if [ "${parts[1]}" = "PLUGIN" ]; then
      plugin_name=$(echo "${parts[2]}" | tr '[:upper:]' '[:lower:]')
      plugin_key=$(join_by _ "${parts[@]:3}" | tr '[:upper:]' '[:lower:]')
      echo "\$conf['plugin']['$plugin_name']['$plugin_key'] = '${!var_name}';"
      echo "\$conf['plugin']['$plugin_name']['$plugin_key'] = '${!var_name}';" >> "$dokuwiki_local_conf"
    else
      config_key=$(join_by _ "${parts[@]:1}" | tr '[:upper:]' '[:lower:]')
      echo "\$conf['$config_key'] = '${!var_name}';"
      echo "\$conf['$config_key'] = '${!var_name}';" >> "$dokuwiki_local_conf"
    fi
  done
}

export ISOWIKI_ROOT_DIR="/opt/isowiki"
export ISOWIKI_VOLUME_DIR="/isowiki"
export APACHE_SERVER_ROOT="/var/www/html"

PERSIST="${PERSIST:-1}"
DEBUG="${DEBUG:-0}"

echo "** Initializing IsoWiki **"

# Copy isowiki files to server configuration
if [ ! -f $APACHE_SERVER_ROOT/doku.php ]; then
   echo "Initializing isowiki"
  # Initializing isowiki
  rm -r $APACHE_SERVER_ROOT
  cp -a $ISOWIKI_ROOT_DIR $APACHE_SERVER_ROOT
  chown -R www-data:www-data $APACHE_SERVER_ROOT
fi

restore_persisted_isowiki () {
  rm -r $APACHE_SERVER_ROOT/data
  ln -s $ISOWIKI_VOLUME_DIR/data $APACHE_SERVER_ROOT/data

  rm -r $APACHE_SERVER_ROOT/conf
  ln -s $ISOWIKI_VOLUME_DIR/conf $APACHE_SERVER_ROOT/conf
}

if [ "$PERSIST" = 1 ]; then
  if [ "$(ls -A $ISOWIKI_VOLUME_DIR)" ]; then
    echo "Restoring persisted IsoWiki installation"
    restore_persisted_isowiki

  else
    echo "Persisting IsoWiki installation"
    cp -a $ISOWIKI_ROOT_DIR/data $ISOWIKI_VOLUME_DIR/data
    chown -R www-data:www-data $ISOWIKI_VOLUME_DIR/data

    cp -a $ISOWIKI_ROOT_DIR/conf $ISOWIKI_VOLUME_DIR/conf
    chown -R www-data:www-data $ISOWIKI_VOLUME_DIR/conf

    restore_persisted_isowiki
  fi
else
  echo "PERSIST=0. The data will be dropped with container."
fi

if [ "$DEBUG" = 1 ]; then
  echo "Debug mode"
  cp "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
  cat >"$PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini" <<EOL
zend_extension=xdebug
xdebug.mode=debug
xdebug.start_with_request=yes
xdebug.discover_client_host=yes
EOL
else
  echo "Production mode"
  cp "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
  rm "$PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini"
fi

# After selecting mode set timezone
cat >"$PHP_INI_DIR/conf.d/tzone.ini" <<EOL
[PHP]
date.timezone = "Europe/Warsaw"
EOL

echo "** IsoWiki initialized **"

echo "** Applying global conf **"
apply_default_config
echo "** Global conf applied **"

service cron start
apache2-foreground