#!/bin/bash

if [ "$DEBUG" = true ]; then
  echo "DEBUG MODE"
  cp "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
  cat >"$PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini" <<EOL
zend_extension=xdebug
xdebug.mode=debug
xdebug.start_with_request=yes
xdebug.discover_client_host=yes
EOL
else
  echo "PRODUCTION MODE"
  cp "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
  rm "$PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini"
fi

service cron start
apache2-foreground