#!/bin/bash

export ISOWIKI_ROOT_DIR="/opt/isowiki"
export ISOWIKI_VOLUME_DIR="/isowiki"
export APACHE_SERVER_ROOT="/var/www/html"

PERSIST="${PERSIST:-1}"
DEBUG="${DEBUG:-0}"

echo "** Initializing IsoWiki **"

# Copy isowiki files to server configuration
if [ ! -f $APACHE_SERVER_ROOT/doku.php ]; then
   echo "Initializing isowiki"
  # Initializing isowiki
  rm -r $APACHE_SERVER_ROOT
  cp -a $ISOWIKI_ROOT_DIR $APACHE_SERVER_ROOT
  chown -R www-data:www-data $APACHE_SERVER_ROOT
fi

restore_persisted_isowiki () {
  rm -r $APACHE_SERVER_ROOT/data
  ln -s $ISOWIKI_VOLUME_DIR/data $APACHE_SERVER_ROOT/data

  rm -r $APACHE_SERVER_ROOT/conf
  ln -s $ISOWIKI_VOLUME_DIR/conf $APACHE_SERVER_ROOT/conf
}

if [ "$PERSIST" = 1 ]; then
  if [ "$(ls -A $ISOWIKI_VOLUME_DIR)" ]; then
    echo "Restoring persisted IsoWiki installation"
    restore_persisted_isowiki

  else
    echo "Persisting IsoWiki installation"
    cp -a $ISOWIKI_ROOT_DIR/data $ISOWIKI_VOLUME_DIR/data
    chown -R www-data:www-data $ISOWIKI_VOLUME_DIR/data

    cp -a $ISOWIKI_ROOT_DIR/conf $ISOWIKI_VOLUME_DIR/conf
    chown -R www-data:www-data $ISOWIKI_VOLUME_DIR/conf

    restore_persisted_isowiki
  fi
else
  echo "PERSIST=0. The data will be dropped with container."
fi

if [ "$DEBUG" = 1 ]; then
  echo "Debug mode"
  cp "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"
  cat >"$PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini" <<EOL
zend_extension=xdebug
xdebug.mode=debug
xdebug.start_with_request=yes
xdebug.discover_client_host=yes
EOL
else
  echo "Production mode"
  cp "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
  rm "$PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini"
fi

# After selecting mode set timezone
cat >"$PHP_INI_DIR/conf.d/tzone.ini" <<EOL
[PHP]
date.timezone = "Europe/Warsaw"
EOL

echo "** IsoWiki initialized **"

service cron start
apache2-foreground